#!/bin/sh
# SAUER_DATA should refer to the directory in which Sauerbraten data files are placed.
#SAUER_DATA=~/sauerbraten
#SAUER_DATA=/usr/local/sauerbraten
SAUER_DATA=.

# SAUER_BIN should refer to the directory in which Sauerbraten executable files are placed.
SAUER_BIN=${SAUER_DATA}/bin

# SAUER_OPTIONS contains any command line options you would like to start Sauerbraten with.
#SAUER_OPTIONS="-f"
#SAUER_OPTIONS="-q${HOME}/.sauerbraten -r" # remove # for normal use
SAUER_OPTIONS="-f -r -qgraphox"

export PATH="${PATH}:."
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:bin:lib"

if [ -x ${SAUER_BIN}/graphox_client ]
then
  cd ${SAUER_DATA}
  gdb -batch -x ${SAUER_BIN}/graphox_client --args "${SAUER_OPTIONS} \"$@\""
else
  echo "Your platform does not have a pre-compiled Sauerbraten client."
  echo "Please follow the following steps to build a native client:"
  echo "1) Ensure you have the SDL, SDL-image, SDL-mixer, and OpenGL libraries installed."
  echo "2) run \"sh compile.sh\"."
  echo "3) If the build succeeds, run this script again."
  exit 1
fi

